version: "3.8"

services:
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8081:80
    hostname: miladev.net
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: admin-miladev
      WORDPRESS_DB_PASSWORD: miladev@pc00541
      WORDPRESS_DB_NAME: miladev_db
    volumes:
      - ./fe-miladev-blog:/var/www/html # Mount toàn bộ mã nguồn WordPress
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    hostname: db.local
    environment:
      MYSQL_DATABASE: miladev_db
      MYSQL_USER: admin-miladev
      MYSQL_PASSWORD: miladev@pc00541
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_USER: admin-miladev
      MYSQL_PASSWORD: miladev@pc00541
    depends_on:
      - db

volumes:
  db_data:
